spring:
  application:
    name: spring-ai-chat-bot
  ai:
    ollama:
      chat:
#        model: llama3.1
        model: qwen2.5:latest
      embedding:
        model: llama3.1
#        model: nomic-embed-text:latest

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
      enabled: true

logging:
  level:
    org.springframework.web: warn